language: android
notifications:
  email: false
android:
  components:
    - platform-tools
    - build-tools-23.0.2
    - android-23

    # Design Support Library
    - extra-android-m2repository

before_install:
  - cd ./android

script:
  - ./gradlew build