language: android
notifications:
  email: false
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.0
    - android-24

    # Support Library
    - extra-android-support

    # Design Support Library
    - extra-android-m2repository

    # Google Play Services
    - extra-google-m2repository

before_install:
  - cd ./android

script:
  - ./gradlew assemble
