# skip_non_tags: true

environment:
  nodejs_version: "6.2.1"

install:
  - cd desktop
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - cd app
  - ps: Set-AppveyorBuildVariable -Name version -Value (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - cd ..
  - node --version
  - npm --version
  - npm run dist
  - cd dist/win
  - rename *.exe openvr-notifications-desktop-%version%-setup.exe
  - move openvr-notifications-desktop-%version%-setup.exe ../../..
  - move openvr-notifications-desktop-%version%-delta.nupkg ../../..
  - move openvr-notifications-desktop-%version%-full.nupkg ../../..
  - move RELEASES ../../..
  - cd ../..
  - rmdir dist /s /q


artifacts:
  - path: '*.exe'
  - path: '*.nupkg'
  - path: RELEASES

deploy:
  release: Version $(version)
  description: 'Description'
  provider: GitHub
  auth_token:
    secure: 4LcQfItsHFXJHdZm9zZxPj33rzkb9kZ74fe+kXcbP5g6BkUsEeRsoZG/INVGuEIl
  artifact: /.*\.exe/,/.*\.nupkg/,RELEASES           
  draft: true
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
